version: 0.2

env:
  variables:
    AWS_REGION: "ap-northeast-2"
    ECR_REGISTRY: "954976330162.dkr.ecr.ap-northeast-2.amazonaws.com"
    ECR_REPOSITORY: "fire-walker/user-ms"

phases:
  install:
    runtime-versions:
      nodejs: 18

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image for user-ms...
      - docker build -f services/user-ms/Dockerfile -t user-ms services/user-ms
      - docker tag user-ms:latest $ECR_REGISTRY/$ECR_REPOSITORY:latest

  post_build:
    commands:
      - echo Pushing the Docker image to ECR...
      - docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
      - echo Build and push completed on `date`

artifacts:
  files:
    - "**/*"
