version: '4.0'
services:
  db:
    image: mysql:8.0
    container_name: mysql_container
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - '3306:3306'
    volumes:
      - ./mysql_data:/var/lib/mysql

    command: --default-authentication-plugin=mysql_native_password


  redis:
    image: redis:7-alpine
    container_name: redis_container
    restart: unless-stopped
    env_file:
      - .env

    ports:
      - '6379:6379'
    volumes:
      - ./redis_data:/data

  web:
    build: .
    container_name: nestjs_container
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - '${APP_PORT}:3000'
    depends_on:
      - db
      - redis
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: ["npm", "run", "start:dev"] # 개발 모드

volumes:
  db_data:
  redis_data:
